### ISSUE TITLE
Error in attachement model

### ISSUE THREAD

**Issue by lion01** [Harmageddon/com_monitor#8]
Hello,
I tested the component in local server (wamp, php 5.5.12) and when try to post issue in backend or in frontend i get this error 

Parse error: syntax error, unexpected '.', expecting ',' or ';' in C:\wamp\www\Joomla35\administrator\components\com_monitor\model\attachments.php on line 18
any fix for this?
thank you, regards

**Comment by Harmageddon** [comment]
Hi!
Thank you for testing this component, I'm glad to hear this! 
I will have a deeper look into your issue this evening. On a quick look into the line mentioned in the error, I can't see any potential problem there, but I will check this later. Could you please look if the file is corrupted? It should look like [this one](https://github.com/Harmageddon/com_monitor/blob/master/admin/model/attachments.php). Maybe there was some problem at the download or file transfer.

**Comment by Harmageddon** [comment]
Hi!
Please forget my last comment... I found the issue, it should be fixed now. Please test the updated version of the master branch. 
Thank you for noticing the issue and reporting it! I was developing with a newer PHP version, where the line worked that way, but it seems to be an issue for "older" versions.

**Comment by lion01** [comment]
Hello thank you for your replay,
adding  the constructor to the class
correct the display issue submission form, but the registration of a new issue fails (without any error message) and redirect to the issue submission form again.
