### ISSUE TITLE
issue submission does not work

### ISSUE THREAD

**Issue by lion01** [Harmageddon/com_monitor#9]
Hello thank you for your replay,
adding the constructor to the class correct the display issue submission form, but the registration of a new issue fails (without any error message) and redirect to the issue submission form again.
regards

**Comment by Harmageddon** [comment]
Hi!
Again: Thank you very much for your report! This behavior occured when a user tried to upload an unsafe file (like PHP files) but the filter didn't post an error message on failure. Does the latest commit solve your problem?
